# Generated by Django 2.2 on 2021-08-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_auto_20210829_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='IMAGE',
            field=models.URLField(blank=True, null=True),
        ),
    ]
